#!/bin/bash

# pip install pdoc3
# note this needs to be run on the pi where all the code can execute sucessfully 

$(mkdir $(pwd)/documentation);

$(pdoc --html $(pwd) --output-dir $(pwd)/documentation)
