#!/bin/bash

# pip3 install pdoc3
# note this needs to be run on the pi where all the code can execute sucessfully 

$(mkdir $(pwd)/documentation);

$(PYTHONPATH=$(pwd) pdoc $(pwd) --output-dir $(pwd)/documentation)
